import nodemailer from 'nodemailer';

export const sendPasswordByEmail = async (email: string, password: string): Promise<void> => {
  try {
    const transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: 'abarnarajanait@gmail.com',
        pass: 'oewwdkmtoojbuocz'
      }
    });

    await transporter.sendMail({
      from: 'abarnarajanait@gmail.com',
      to: email,
      subject: 'Password to login',
      text: `Your autogenerated password is: ${password}`
    });

    console.log('Password sent to email:', email);
  } catch (error) {
    console.error('Email sending error:', error);
    throw new Error('Failed to send password email');
  }
};
// export const sendSuccessEmail = async (email: string): Promise<void> => {
//   try {
//     const transporter = nodemailer.createTransport({
//       service: 'gmail',
//       auth: {
//         user: 'abarnarajanait@gmail.com',
//         pass: 'oewwdkmtoojbuocz'
//       }
//     });

//     const mailOptions = {
//       from: 'abarnarajanait@gmail.com',
//       to: email, // Make sure 'email' parameter is correctly passed and is a valid email address
//       subject: 'Login Successful',
//       text: 'Thanks for Registering....',
//       html: '<p>Welcome to our App</p>' // You can use HTML for the email body
//     };

//     await transporter.sendMail(mailOptions);

//     console.log('Thanks note sent to email:', email);
//   } catch (error) {
//     console.error('Email sending error:', error);
//     throw new Error('Failed to send Thanks note email');
//   }
// };
export const generatePassword = (): string => {
  return Math.random().toString(36).slice(-8); 
};
export const verifyOTP = async (email: string, otp: string): Promise<boolean> => {
    
    const storedOTP = '123456'; 
    return otp === storedOTP;
  };
  export const sendOTP = async (email: string, otp: string): Promise<void> => {
    try {
      const transporter = nodemailer.createTransport({
        service: 'gmail',
        auth: {
          user: 'abarnarajanait@gmail.com',
          pass: 'oewwdkmtoojbuocz'
        }
      });
  
      await transporter.sendMail({
        from: 'abarnarajanait@gmail.com',
        to: email,
        subject: 'Your OTP Code',
        text: `Your OTP code is: ${otp}`
      });
  
      console.log('OTP sent to email:', email);
    } catch (error) {
      console.error('Email sending error:', error);
      throw new Error('Failed to send OTP email');
    }
  };
  export const generateOTP = (): string => {
    return Math.floor(100000 + Math.random() * 900000).toString(); // Generates a 6-digit OTP
  };